function [featureTable,outputTable] = diagnosticFeatures(inputData)
%DIAGNOSTICFEATURES recreates results in Diagnostic Feature Designer.
%
% Input:
%  inputData: A table or a cell array of tables/matrices containing the
%  data as those imported into the app.
%
% Output:
%  featureTable: A table containing all features and condition variables.
%  outputTable: A table containing the computation results.
%
% This function computes spectra:
%  flow_ps/SpectrumData
%  pressure_ps/SpectrumData
%
% This function computes features:
%  flow_sigstats/Mean
%  flow_sigstats/RMS
%  flow_tsfeat/Median
%  flow_tsfeat/Q1
%  flow_tsfeat/Q3
%  flow_tsmodel/Coef1
%  flow_tsmodel/Mean
%  flow_tsmodel/RMS
%  pressure_sigstats/Mean
%  pressure_sigstats/RMS
%  pressure_tsfeat/Median
%  pressure_tsfeat/Q1
%  pressure_tsfeat/Q3
%  pressure_tsmodel/Mean
%  pressure_tsmodel/RMS
%  pressure_tsmodel/Kurtosis
%  pressure_ps_spec/PeakAmp1
%  pressure_ps_spec/BandPower
%  flow_ps_spec/PeakAmp1
%  flow_ps_spec/BandPower
%
% Organization of the function:
% 1. Compute signals/spectra/features
% 2. Extract computed features into a table
%
% Modify the function to add or remove data processing, feature generation
% or ranking operations.

% Auto-generated by MATLAB on 06-Oct-2025 15:02:23

% Create output ensemble.
outputEnsemble = workspaceEnsemble(inputData,'DataVariables',["flow";"pressure"],'ConditionVariables',"faultCode");

% Reset the ensemble to read from the beginning of the ensemble.
reset(outputEnsemble);

% Append new signal or feature names to DataVariables.
outputEnsemble.DataVariables = unique([outputEnsemble.DataVariables;"flow_ps";"pressure_ps";"flow_sigstats";"flow_tsfeat";"flow_tsmodel";"pressure_sigstats";"pressure_tsfeat";"pressure_tsmodel";"pressure_ps_spec";"flow_ps_spec"],'stable');

% Set SelectedVariables to select variables to read from the ensemble.
outputEnsemble.SelectedVariables = ["flow","pressure"];

% Initialize a cell array to store all the results.
allMembersResult = {};

% Loop through all ensemble members to read and write data.
while hasdata(outputEnsemble)
    % Read one member.
    member = read(outputEnsemble);

    % Get all input variables.
    flow = readMemberData(member,"flow",["Time","Data"]);
    pressure = readMemberData(member,"pressure",["Time","Data"]);

    % Initialize a table to store results.
    memberResult = table;

    %% PowerSpectrum
    try
        % Get units to use in computed spectrum.
        tuReal = "seconds";

        % Compute effective sampling rate.
        tNumeric = time2num(flow.Time,tuReal);
        [Fs,irregular] = effectivefs(tNumeric);
        Ts = 1/Fs;

        % Resample non-uniform signals.
        x_raw = flow.Data;
        if irregular
            x = resample(x_raw,tNumeric,Fs,'linear');
        else
            x = x_raw;
        end

        % Set Welch spectrum parameters.
        L = fix(length(x)/4.5);
        noverlap = fix(L*50/100);
        win = hamming(L);

        % Compute the power spectrum.
        [ps,f] = pwelch(x,win,noverlap,[],Fs);
        w = 2*pi*f;

        % Convert frequency unit.
        factor = funitconv('rad/TimeUnit', 'Hz', 'seconds');
        w = factor*w;
        Fs = 2*pi*factor*Fs;

        % Remove frequencies above Nyquist frequency.
        I = w<=(Fs/2+1e4*eps);
        w = w(I);
        ps = ps(I);

        % Configure the computed spectrum.
        ps = table(w, ps, 'VariableNames', {'Frequency', 'SpectrumData'});
        ps.Properties.VariableUnits = {'Hz', ''};
        ps = addprop(ps, {'SampleFrequency'}, {'table'});
        ps.Properties.CustomProperties.SampleFrequency = Fs;
        flow_ps = ps;
    catch
        flow_ps = table(NaN, NaN, 'VariableNames', {'Frequency', 'SpectrumData'});
    end

    % Append computed results to the member table.
    memberResult = [memberResult, ...
        table({flow_ps},'VariableNames',{'flow_ps'})]; %#ok<AGROW>

    %% PowerSpectrum
    try
        % Get units to use in computed spectrum.
        tuReal = "seconds";

        % Compute effective sampling rate.
        tNumeric = time2num(pressure.Time,tuReal);
        [Fs,irregular] = effectivefs(tNumeric);
        Ts = 1/Fs;

        % Resample non-uniform signals.
        x_raw = pressure.Data;
        if irregular
            x = resample(x_raw,tNumeric,Fs,'linear');
        else
            x = x_raw;
        end

        % Set Welch spectrum parameters.
        L = fix(length(x)/4.5);
        noverlap = fix(L*50/100);
        win = hamming(L);

        % Compute the power spectrum.
        [ps,f] = pwelch(x,win,noverlap,[],Fs);
        w = 2*pi*f;

        % Convert frequency unit.
        factor = funitconv('rad/TimeUnit', 'Hz', 'seconds');
        w = factor*w;
        Fs = 2*pi*factor*Fs;

        % Remove frequencies above Nyquist frequency.
        I = w<=(Fs/2+1e4*eps);
        w = w(I);
        ps = ps(I);

        % Configure the computed spectrum.
        ps = table(w, ps, 'VariableNames', {'Frequency', 'SpectrumData'});
        ps.Properties.VariableUnits = {'Hz', ''};
        ps = addprop(ps, {'SampleFrequency'}, {'table'});
        ps.Properties.CustomProperties.SampleFrequency = Fs;
        pressure_ps = ps;
    catch
        pressure_ps = table(NaN, NaN, 'VariableNames', {'Frequency', 'SpectrumData'});
    end

    % Append computed results to the member table.
    memberResult = [memberResult, ...
        table({pressure_ps},'VariableNames',{'pressure_ps'})]; %#ok<AGROW>

    %% SignalFeatures
    try
        % Compute signal features.
        inputSignal = flow.Data;
        Mean = mean(inputSignal,'omitnan');
        RMS = rms(inputSignal,'omitnan');

        % Concatenate signal features.
        featureValues = [Mean,RMS];

        % Store computed features in a table.
        featureNames = {'Mean','RMS'};
        flow_sigstats = array2table(featureValues,'VariableNames',featureNames);
    catch
        % Store computed features in a table.
        featureValues = NaN(1,2);
        featureNames = {'Mean','RMS'};
        flow_sigstats = array2table(featureValues,'VariableNames',featureNames);
    end

    % Append computed results to the member table.
    memberResult = [memberResult, ...
        table({flow_sigstats},'VariableNames',{'flow_sigstats'})]; %#ok<AGROW>

    %% TimeSeriesFeatures
    try
        % Compute time series features.
        inputSignal = flow.Data;
        quartiles = quantile(inputSignal, [0.25 0.5 0.75]);

        % Extract individual feature values.
        Median = median(inputSignal, 'omitnan');
        Q1 = quartiles(1);
        Q3 = quartiles(3);

        % Concatenate signal features.
        featureValues = [Median,Q1,Q3];

        % Store computed features in a table.
        featureNames = {'Median','Q1','Q3'};
        flow_tsfeat = array2table(featureValues,'VariableNames',featureNames);
    catch
        % Store computed features in a table.
        featureValues = NaN(1,3);
        featureNames = {'Median','Q1','Q3'};
        flow_tsfeat = array2table(featureValues,'VariableNames',featureNames);
    end

    % Append computed results to the member table.
    memberResult = [memberResult, ...
        table({flow_tsfeat},'VariableNames',{'flow_tsfeat'})]; %#ok<AGROW>

    %% TimeSeriesModelFeatures
    try
        % Compute model-based time series features.
        x = flow.Data;
        t = flow.Time;
        y = x - mean(x,'omitnan');
        N = numel(x);

        % Estimate autoregressive model.
        p = 10;
        R = xcorr(y,p,'biased');
        R(1:p) = [];
        [a,Ep] = levinson(R,p);

        % Compute effective sampling rate.
        tNumeric = time2num(t,"seconds");
        Fs = effectivefs(tNumeric);

        % Compute model poles.
        r = sort(roots(a),'descend');
        s = Fs*log(r);
        Fn = abs(s)/2/pi;
        Zn = -real(s)./abs(s);

        % Estimate process noise.
        w = filter(a,1,y);

        % Estimate model residuals.
        e = filter(a,1,x);

        % Extract individual feature values.
        Coef1 = a(2);
        Mean = mean(e,'omitnan');
        RMS = rms(e,'omitnan');

        % Concatenate signal features.
        featureValues = [Coef1,Mean,RMS];

        % Store computed features in a table.
        featureNames = {'Coef1','Mean','RMS'};
        flow_tsmodel = array2table(featureValues,'VariableNames',featureNames);
    catch
        % Store computed features in a table.
        featureValues = NaN(1,3);
        featureNames = {'Coef1','Mean','RMS'};
        flow_tsmodel = array2table(featureValues,'VariableNames',featureNames);
    end

    % Append computed results to the member table.
    memberResult = [memberResult, ...
        table({flow_tsmodel},'VariableNames',{'flow_tsmodel'})]; %#ok<AGROW>

    %% SignalFeatures
    try
        % Compute signal features.
        inputSignal = pressure.Data;
        Mean = mean(inputSignal,'omitnan');
        RMS = rms(inputSignal,'omitnan');

        % Concatenate signal features.
        featureValues = [Mean,RMS];

        % Store computed features in a table.
        featureNames = {'Mean','RMS'};
        pressure_sigstats = array2table(featureValues,'VariableNames',featureNames);
    catch
        % Store computed features in a table.
        featureValues = NaN(1,2);
        featureNames = {'Mean','RMS'};
        pressure_sigstats = array2table(featureValues,'VariableNames',featureNames);
    end

    % Append computed results to the member table.
    memberResult = [memberResult, ...
        table({pressure_sigstats},'VariableNames',{'pressure_sigstats'})]; %#ok<AGROW>

    %% TimeSeriesFeatures
    try
        % Compute time series features.
        inputSignal = pressure.Data;
        quartiles = quantile(inputSignal, [0.25 0.5 0.75]);

        % Extract individual feature values.
        Median = median(inputSignal, 'omitnan');
        Q1 = quartiles(1);
        Q3 = quartiles(3);

        % Concatenate signal features.
        featureValues = [Median,Q1,Q3];

        % Store computed features in a table.
        featureNames = {'Median','Q1','Q3'};
        pressure_tsfeat = array2table(featureValues,'VariableNames',featureNames);
    catch
        % Store computed features in a table.
        featureValues = NaN(1,3);
        featureNames = {'Median','Q1','Q3'};
        pressure_tsfeat = array2table(featureValues,'VariableNames',featureNames);
    end

    % Append computed results to the member table.
    memberResult = [memberResult, ...
        table({pressure_tsfeat},'VariableNames',{'pressure_tsfeat'})]; %#ok<AGROW>

    %% TimeSeriesModelFeatures
    try
        % Compute model-based time series features.
        x = pressure.Data;
        t = pressure.Time;
        y = x - mean(x,'omitnan');
        N = numel(x);

        % Estimate autoregressive model.
        p = 10;
        R = xcorr(y,p,'biased');
        R(1:p) = [];
        [a,Ep] = levinson(R,p);

        % Compute effective sampling rate.
        tNumeric = time2num(t,"seconds");
        Fs = effectivefs(tNumeric);

        % Compute model poles.
        r = sort(roots(a),'descend');
        s = Fs*log(r);
        Fn = abs(s)/2/pi;
        Zn = -real(s)./abs(s);

        % Estimate process noise.
        w = filter(a,1,y);

        % Estimate model residuals.
        e = filter(a,1,x);

        % Extract individual feature values.
        Mean = mean(e,'omitnan');
        RMS = rms(e,'omitnan');
        Kurtosis = kurtosis(e);

        % Concatenate signal features.
        featureValues = [Mean,RMS,Kurtosis];

        % Store computed features in a table.
        featureNames = {'Mean','RMS','Kurtosis'};
        pressure_tsmodel = array2table(featureValues,'VariableNames',featureNames);
    catch
        % Store computed features in a table.
        featureValues = NaN(1,3);
        featureNames = {'Mean','RMS','Kurtosis'};
        pressure_tsmodel = array2table(featureValues,'VariableNames',featureNames);
    end

    % Append computed results to the member table.
    memberResult = [memberResult, ...
        table({pressure_tsmodel},'VariableNames',{'pressure_tsmodel'})]; %#ok<AGROW>

    %% SpectrumFeatures
    try
        % Compute spectral features.
        % Get frequency unit conversion factor.
        factor = funitconv('Hz', 'rad/TimeUnit', 'seconds');
        ps = pressure_ps.SpectrumData;
        w = pressure_ps.Frequency;
        w = factor*w;
        mask_1 = (w>=factor*0) & (w<=factor*500);
        ps = ps(mask_1);
        w = w(mask_1);

        % Compute spectral peaks.
        [peakAmp,peakFreq] = findpeaks(ps,w/factor,'MinPeakHeight',-Inf, ...
            'MinPeakProminence',0,'MinPeakDistance',0.001,'SortStr','descend','NPeaks',1);
        peakAmp = [peakAmp(:); NaN(1-numel(peakAmp),1)];
        peakFreq = [peakFreq(:); NaN(1-numel(peakFreq),1)];

        % Extract individual feature values.
        PeakAmp1 = peakAmp(1);
        BandPower = trapz(w/factor,ps);

        % Concatenate signal features.
        featureValues = [PeakAmp1,BandPower];

        % Store computed features in a table.
        featureNames = {'PeakAmp1','BandPower'};
        pressure_ps_spec = array2table(featureValues,'VariableNames',featureNames);
    catch
        % Store computed features in a table.
        featureValues = NaN(1,2);
        featureNames = {'PeakAmp1','BandPower'};
        pressure_ps_spec = array2table(featureValues,'VariableNames',featureNames);
    end

    % Append computed results to the member table.
    memberResult = [memberResult, ...
        table({pressure_ps_spec},'VariableNames',{'pressure_ps_spec'})]; %#ok<AGROW>

    %% SpectrumFeatures
    try
        % Compute spectral features.
        % Get frequency unit conversion factor.
        factor = funitconv('Hz', 'rad/TimeUnit', 'seconds');
        ps = flow_ps.SpectrumData;
        w = flow_ps.Frequency;
        w = factor*w;
        mask_1 = (w>=factor*0) & (w<=factor*500);
        ps = ps(mask_1);
        w = w(mask_1);

        % Compute spectral peaks.
        [peakAmp,peakFreq] = findpeaks(ps,w/factor,'MinPeakHeight',-Inf, ...
            'MinPeakProminence',0,'MinPeakDistance',0.001,'SortStr','descend','NPeaks',1);
        peakAmp = [peakAmp(:); NaN(1-numel(peakAmp),1)];
        peakFreq = [peakFreq(:); NaN(1-numel(peakFreq),1)];

        % Extract individual feature values.
        PeakAmp1 = peakAmp(1);
        BandPower = trapz(w/factor,ps);

        % Concatenate signal features.
        featureValues = [PeakAmp1,BandPower];

        % Store computed features in a table.
        featureNames = {'PeakAmp1','BandPower'};
        flow_ps_spec = array2table(featureValues,'VariableNames',featureNames);
    catch
        % Store computed features in a table.
        featureValues = NaN(1,2);
        featureNames = {'PeakAmp1','BandPower'};
        flow_ps_spec = array2table(featureValues,'VariableNames',featureNames);
    end

    % Append computed results to the member table.
    memberResult = [memberResult, ...
        table({flow_ps_spec},'VariableNames',{'flow_ps_spec'})]; %#ok<AGROW>

    % Append all member results to the cell array.
    allMembersResult = [allMembersResult; {memberResult}]; %#ok<AGROW>
end

% Write the results for all members to the ensemble.
writeToMembers(outputEnsemble,allMembersResult)

% Gather all features into a table.
selectedFeatureNames = ["flow_sigstats/Mean","flow_sigstats/RMS","flow_tsfeat/Median","flow_tsfeat/Q1","flow_tsfeat/Q3","flow_tsmodel/Coef1","flow_tsmodel/Mean","flow_tsmodel/RMS","pressure_sigstats/Mean","pressure_sigstats/RMS","pressure_tsfeat/Median","pressure_tsfeat/Q1","pressure_tsfeat/Q3","pressure_tsmodel/Mean","pressure_tsmodel/RMS","pressure_tsmodel/Kurtosis","pressure_ps_spec/PeakAmp1","pressure_ps_spec/BandPower","flow_ps_spec/PeakAmp1","flow_ps_spec/BandPower"];
featureTable = readFeatureTable(outputEnsemble,'Features',selectedFeatureNames);

% Set SelectedVariables to select variables to read from the ensemble.
outputEnsemble.SelectedVariables = unique([outputEnsemble.DataVariables;outputEnsemble.ConditionVariables;outputEnsemble.IndependentVariables],'stable');

% Gather results into a table.
if nargout > 1
    outputTable = readall(outputEnsemble);
end
end